### Inicio
GET http://localhost:3000/

### Obtener toda la lista de los productos
GET http://localhost:3000/productos

### Obtener toda la lista de los productos segun su categoria
GET http://localhost:3000/productos?categoria=portatiles

### Obtener los productos buscando por su nombre (incluir tildes)
GET http://localhost:3000/productos?nombre=Cámara web


### Obtener un producto por su id (Llamado Codigo en la db)
GET http://localhost:3000/productos/28

### Agregar productos
POST http://localhost:3000/productos/create
Content-Type: application/json

 {
    "nombre": "Botonera ElPerico",
    "precio": 325,
    "categoria": "Accesorios"
 }

###Editar el precio de un producto
PATCH http://localhost:3000/productos/edit/66a97a3a5ce0fdf7d3e02f3e
Content-Type: application/json

{
    "precio": 669
 }

###Borrar producto por su _id
DELETE http://localhost:3000/productos/6699762453b9e7a3dd276c7c